### ISSUE TITLE
Configs are not applied to modules on start

### ISSUE THREAD

**Issue by UnnamedOrange** [VortexCoyote/leraine-studio#51]
For example:
https://github.com/VortexCoyote/leraine-studio/blob/503ced948dc6f3db306352796a60788cfe6e5dd7/source/program/program.cpp#L240

Only here the UsePitch of AudioModule is modified. When the config file is load on the launch of the application, it is not applied to AudioModule. Note that there are other such options sharing the same problem.

**Comment by Opposite34** [comment]
Seems like everything apart from Waveform isn't load on launch. Might need some restructure a bit.
